### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mjmasn** [lostpebble/generate-package-json-webpack-plugin#4] opened 2017-12-08 20:42 UTC
I'm getting the following error in webpack watch mode. The first run works fine but after editing a file it crashes.

```
TypeError: Cannot read property 'length' of undefined
    at Compiler.compiler.plugin ({REMOVED}/node_modules/generate-package-json-webpack-plugin/index.js:112:61)
```

The line in question is:
```
if (this.otherPackageValues.dependencies[moduleName].length > 0) { ... }
```

In my case seems on the second run the `nonWebpackModuleNames` array and therefore `moduleName` ends up containing `path` (as in the built-in node module) but the problem is reproducible with any other built in module like `fs` that happens to be imported into the code. Should these modules be excluded somehow, or is this a webpack issue returning the wrong information on the second run?

**Comment by lostpebble** [comment] 2017-12-11 08:32
@mjmasn I like the changes you made which double check if there is a dependency in the source package.json before adding it to the list to be placed in the generated package.json. Usually those dependencies with undefined versions were cleared out at a later stage.

But from what I can see, that line that's causing the error seems to be unrelated, because it's in the part of the plugin that adds extra dependencies that you've explicitly stated in your "blueprint" package.json object that you pass in as the first parameter.

That `nonWebpackModuleNames` is pulled from that object, so it's strange that it's causing issues with built-in modules. Are you passing anything in your `basePackageValues` under `dependencies: {}`? Like so:

```
const basePackageValues = {
  "name": "my-nodejs-module",
  "version": "1.0.0",
  "main": "./index.js",
  "scripts": {
    "start": "cross-var node --max-old-space-size=$NODE_JS_MAX_OLD_SPACE_SIZE ./server.js"
  }
  "engines": {
    "node": "<= 6.9.1"
  },
  dependencies: {
    "cross-var": "^1.1.0",
    "cross-env": "",
  },
}

...

plugins: [
   new GeneratePackageJsonPlugin(basePackageValues, versionsPackageFilename),
   ...
]

```

I'll accept your pull request for those changes, I just wonder if that's the root cause here.

**Comment by lostpebble** [comment] 2017-12-11 08:40
Re-opening until we're sure those changes fixed the root cause of this problem.

**Comment by lostpebble** [comment] 2017-12-11 08:46
Also, I'd like to add - while it's by no means dismissing this issue and I'd like to get to the bottom of it - that generating a new package.json probably should be done in a single production build step? That's the way I've always been testing this plugin on my side.

I'm unsure of the benefits of doing it while watching. Unless you only have a single webpack configuration and don't want to split it out - which is fair.

**Comment by mjmasn** [comment] 2017-12-11 11:02
@lostpebble fair points, and thanks for merging the PR. I am trying to remember why the `package.json` is being generated on watch because it isn't actually used for development. I think it was just for testing when I initially added the package without running a production build each time. The usefulness of doing that now is probably less clear. I actually have 4 webpack configs for dev client/server (watch mode) and prd client/server (single build, production mode) and the two server ones are using this plugin.

Btw I'm actually passing in an actual package.json with no dependencies as the `basePackageValues` (by `require`-ing it), then the filename for a higher-level package.json as the `versionsPackageFilename`. The reason being I have a load of apps/services/websites in a single git repo with the 4 shared webpack configs and a shared main package.json to keep all dependencies in sync/in one place then an individual package.json per service just with the service name and scripts. That's probably weird but shouldn't matter here.

I think the issue is technically caused by this line: https://github.com/lostpebble/generate-package-json-webpack-plugin/blob/0ed6396929a50c9edaded8c657791564b9610464/index.js#L126 which explains why it works once then fails (because it occurs after the line that was throwing an error - https://github.com/lostpebble/generate-package-json-webpack-plugin/blob/0ed6396929a50c9edaded8c657791564b9610464/index.js#L114) . The modules object is generated from the webpack output and includes built in modules. That could possibly be a misconfiguration on my end though? I'm very much at the try-stuff-till-it-stops-breaking level of understanding Webpack 😬

**Comment by lostpebble** [comment] 2017-12-13 12:27
> Btw I'm actually passing in an actual package.json with no dependencies as the basePackageValues (by require-ing it)

Ahh, that's actually quite an interesting way to interact with the plugin. Never actually thought about doing that, but it makes complete sense - also can get some nice IDE auto-completion for `package.json` values that way.

> I think the issue is technically caused by this line

Good find. Yes that is most probably it, because it's assigning to that same object (mutating that object) instead of creating a new one, it is persisting on the next build cycle with unexpected values.

I'm gonna write a quick fix for this. Thanks for the discovery!

> I'm very much at the try-stuff-till-it-stops-breaking level of understanding Webpack 😬

Aren't we all... 😅

**Closed as completed** 2017-12-13 12:32 UTC
