### ISSUE TITLE
Don't try to resolve package that are already in additionalDependencies

### ISSUE THREAD

**Issue by erlichmen** [lostpebble/generate-package-json-webpack-plugin#34] opened 2021-09-13 13:31 UTC
When using generate-package-json-webpack-plugin on packages that are using firebase-function, I get the error:

`"GPJWP: Ignoring module without a found package.json: firebase-functions ("firebase-functions/package.json" couldn't resolve)"`

The actual error (that is hidden) is:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in <>/node_modules/firebase-functions/package.json`

I never used "exports" in package.json but apparently when you have that require.resolve() will use that to locate package.json and if package.json is not listed there you get the above error.
If you ask me ([and others](https://github.com/nodejs/node/issues/33460)) package.json should not be consider even in "exports", but this is the current state of the node implementation .

As a hack I post process the package.json, a better hack will be that if I provide the package in additionalDependencies, the whole require.resolve should be skipped and take the explicit version.

**Comment by lostpebble** [comment] 2021-09-14 11:22
Hmm this is rather annoying.

Is there no other method we could use to actually get the real `package.json` for the module? Like is there no Nodejs method that gives us the "base folder" of any package... Will have to do some research. Another option could be to create something manual that does the Node lookup process using the file system modules- I'm sure some packages exist to do that too, but I'd like to keep things as lean as possible.

Btw, `additionalDependencies` has been deprecated for a while now. The way to directly add dependencies is to put them directly into the base `package.json` object (the first argument) under either `dependencies` or `devDependencies`. Please check if this works- I _think_ it should. But possibly will need to add this functionality then.

See documentation about that here: https://github.com/lostpebble/generate-package-json-webpack-plugin#adding-modules-outside-of-your-code-build-modules-etc

**Comment by lostpebble** [comment] 2021-09-14 15:08
@erlichmen please try the new version (2.3.0) - I've changed the way it looks up `package.json` files to get around the current Node.js limitations (which I agree is silly and a bit short-sighted considering how modules have been consumed for ages already).

Let me know if that works for you.

**Comment by erlichmen** [comment] 2021-09-14 22:40
@lostpebble yes it fixes my problem, thank you for the prompt response

**Comment by aquacash5** [comment] 2021-09-15 10:42
Just started using this yesterday to generate AWS lambda functions. The plugin got tripped up when I imported `mysql2/promise`. However it didn't throw any errors, the package was just not included in the new package.json file.

This is fixed in the latest update though.

**Comment by erlichmen** [comment] 2021-09-15 10:44
I suggest that errors will not be under the log but under a real console
error output.  This will save you from using debug: true to understand
what's going on.

**Comment by lostpebble** [comment] 2021-09-15 10:50
> 
> 
> Just started using this yesterday to generate AWS lambda functions. The plugin got tripped up when I imported `mysql2/promise`. However it didn't throw any errors, the package was just not included in the new package.json file.
> 
> This is fixed in the latest update though.

That's great to hear- funnily enough, I think the new resolving method solves these issues because of the way it now cuts off the extraneous parts of the import- so `mysql2/promise` will correctly be searching for only `mysql2` instead, and successfully finding the `package.json`.

> I suggest that errors will not be under the log but under a real console
> error output.  This will save you from using debug: true to understand
> what's going on.

While this is a good thing to have for sure- the problem is console output will be massive in some cases because errors are expected to be thrown and caught in certain common scenarios behind the scenes. I think I just need to actually look deeper into recognizing and categorizing the errors that can occur- and for sure directly log ones that are not _known and expected_, such as the `[ERR_PACKAGE_PATH_NOT_EXPORTED]` you ran into.

**Comment by erlichmen** [comment] 2021-10-04 07:05
Sorry to reopen this but I just now, notice the same issue when "@babel/runtime" is required.
I don't require this directly but I need this in runtime.

When I open debug I see:
```
GPJWP: Modules to be used in generated package.json {
  '@babel/runtime': undefined,
```

and in the logs:
```
GPJWP: Ignoring module without a found package.json: @babel/runtime ("@babel/runtime/package.json" couldn't resolve)
```

**Comment by lostpebble** [comment] 2021-10-04 08:03
Hi @erlichmen , no worries- its good to get to the bottom of this stuff.

So, it seems that `@babel/runtime/package.json` can't be resolved. Is this module available to be resolved? That path seems correct, but perhaps its not in Node's module resolve scope for some reason from where Webpack is running. I use the same module and its definitely available at `node_modules/@babel/runtime/package.json` - and _should_ resolve correctly.

**Comment by erlichmen** [comment] 2021-10-04 10:48
Another thing to throw at the mix is the fact that i'm using "yarn workspaces"  I don't know if that has any effect.
The @babel/runtime is at the root workspace node_modules and in the workspace folder it has package.json.

I added conole.error to the catch and I see this:
```
No "exports" main defined <path to workspace package not root>/node_modules/@babel/runtime/package.json
```


Also I think that if getting undefined in (for any package):
```
GPJWP: Modules to be used in generated package.json {
  '@babel/runtime': undefined,
}
```
The process should fail as it means that that module is needed but for some reason couldn't be resolved

**Comment by lostpebble** [comment] 2021-10-04 10:55
> No "exports" main defined <path to workspace package not root>/node_modules/@babel/runtime/package.json

Ahhh... the pain continues with this terrible direction Node.js module resolving is heading. The way to get around the latest changes they made was to resolve the module directly (`@babel/runtime`)- which resolves the "main" file, from which we could deduce the "base" path for the module from which we could resolve the `package.json`. It seems that `@babel/runtime` (and possibly many other such packages) do not define any "main" entry in their `package.json`- so doing something like `require.resolve("@babel/runtime")` actually returns `undefined`.

It seems we may need to implement an even more customized way to do a folder lookup for the modules inside `node_modules`.

> Another thing to throw at the mix is the fact that i'm using "yarn workspaces" I don't know if that has any effect.
> The @babel/runtime is at the root workspace node_modules and in the workspace folder it has package.json.

This is not a problem- the module resolution is designed to crawl up the folder structure as far as it needs to go. I also use Yarn and workspaces.

> The process should fail as it means that that module is needed but for some reason couldn't be resolved

Agreed, I think there is some better error handling that needs to be implemented in this part (although the root of the issue is a bug, so not _really_ an end-user error).

**Comment by lostpebble** [comment] 2021-10-04 12:33
@erlichmen please try the next version `2.4.0` - I've added extra stuff that should catch the errors and find the real path needed. I've also made errors in these cases get output to console.error even if debug is turned off.

**Comment by erlichmen** [comment] 2021-10-04 12:58
Seems to be working (famous last words), thank you.

**Closed as completed** 2021-10-04 13:05 UTC
