### ISSUE TITLE
socket.io dependency

### ISSUE THREAD

**Issue by Mariede** [lostpebble/generate-package-json-webpack-plugin#26] opened 2020-11-26 15:33 UTC
Hi there.. Any idea why it is not adding the socket.io lib to depencies list after bundled?

**Comment by lostpebble** [comment] 2020-11-26 17:26
Hi there,

You'll have to give a little more context about your configuration for me to know what's going on. It be added if its being used in the code you are bundling and the plugin is set up to `useInstalledVersions`. Otherwise, you might be bundling socket.io and it won't be seen as an external dependency.

It depends on your config and setup, so will need to see more context to debug.

**Comment by Mariede** [comment] 2020-11-26 18:22
The lib  is required just like all the other dependencies...

const io = require('socket.io');

and it's not allowed to be bundled in webpack config (for sure it is not)

externals: [
	NodeExternals()
],

funny thing, in a list of about 20 dependencies only socket.io doesn't come anymore. It used to be ok a few time ago... Recently I have updated socket.io to version 3.~ and everything else to latest (webpack, eslint, ...)

I really didn't figured out yet why is this happening... for now I am passing all the dependencies when creating the the package.json.


Thank's

**Comment by Mariede** [comment] 2020-11-27 00:38
Maybe it can help if you want to check the webpack file here:

https://github.com/Mariede/boiler-server/blob/master/.webpack.config.js

The socket.io require really has nothing special with it.. the only thing I can think that differs from other ones is the dot in the name of the lib... very odd. Anyway I will update you if I find something new here. Thank you

**Comment by lostpebble** [comment] 2020-11-27 10:11
Hmm very strange indeed. Would have to run some tests with a new project that includes `socket.io` soon then. Can't think the module name is causing the issue... though anything is possible.

I'm currently very swamped with regular work things, but will try take a look at some point. Otherwise, keep me updated if you discover something.

**Comment by dolanmiu** [comment] 2020-11-27 13:04
We are also having this issue

**Comment by barnabasbartha** [comment] 2020-11-27 13:26
It does not work when set explicitly neither using:
`dependencies: {
'socket.io': '3.0.1'
}`

**Comment by lostpebble** [comment] 2020-11-27 14:38
I've managed to reproduce the problem in one of my projects. Going to take a look now about resolving it, seeing as it seems to be quite widespread.

**Comment by lostpebble** [comment] 2020-11-27 15:12
It all came down to this obscurity:

These two are not equal, in the context of `moduleName = "socket.io"`.

```ts
require.resolve(`${moduleName}/package.json`)
```

```ts
require.resolve(path.join(moduleName, "./package.json"))
```

(the second one is the fix that works for `"socket.io"`)

Very strange, and I guess it did have something to do with the period in the name...

I've pushed an update- please check out `2.1.1` and let me know if there's still any issues.

**Comment by Mariede** [comment] 2020-11-27 16:58
> It all came down to this obscurity:
> 
> These two are not equal, in the context of `moduleName = "socket.io"`.
> 
> ```ts
> require.resolve(`${moduleName}/package.json`)
> ```
> 
> ```ts
> require.resolve(path.join(moduleName, "./package.json"))
> ```
> 
> (the second one is the fix that works for `"socket.io"`)
> 
> Very strange, and I guess it did have something to do with the period in the name...
> 
> I've pushed an update- please check out `2.1.1` and let me know if there's still any issues.

@lostpebble I have checked the build with the new updated plugin and it is working like a charm now. Thank you.

**Closed as completed** 2020-11-27 17:00 UTC
